name: Feature Branching
author: Jonathan Delgado <hi@jon.soy> (https://jon.soy)

branding:
  icon: git-branch
  color: orange

description: Automate merge all branching tagged

inputs:
  label_name_to_merge:
    description: Label used to select branch. Ex. `future-branch`
    required: true
  base_brach:
    description: Branch name used to make the branch. Ex. `master`
    required: true
  destination_brach:
    description: name of branch to merge branches tagged. Per default add the prefix `pre-` at the name base branch. Ex. `pre-master`
    required: false
  with_summary:
    description: If is `true` print a summary on the pipeline
    required: false
    default: "true"

outputs:
  created:
    description: |
      `true` if the feature branch was created, `false` otherwise.

runs:
  using: "node16"
  main: "src/action.js"
